# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aleksandr Demshin
email: demshin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog of Aleksandr Demshin, Systems Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://demsh.in" # the base hostname & protocol for your site
# twitter_username: demshin
github_username: demshin
lang: ru
google_analytics_id: G-XKK8ZMW7D2

# Build settings
markdown: kramdown
timezone: Asia/Yekaterinburg

# При выводе всех постов на одной странице используем постраничный вывод
paginate: 5
paginate_path: "page:num"

# не публиковать посты, указанное время которых позднее времени момента публикации
future: false

theme: jekyll-theme-minimal
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
